
services:
  postgres:
    image: postgres:16
    container_name: cms-postgres
    environment:
      POSTGRES_DB: cms_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # optional but recommended

  redis:
    image: redis:7
    container_name: cms-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: