spring.application.name=cms-backend

server.port=8080

<<<<<<< HEAD
spring.datasource.url=jdbc:postgresql://cmsdb.c72qwa0oy3ht.ap-south-1.rds.amazonaws.com:5432/cmsdb

spring.datasource.username=postgres

spring.datasource.password=daranexuscms

spring.datasource.driver-class-name=org.postgresql.Driver
=======
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://cmsdb.c72qwa0oy3ht.ap-south-1.rds.amazonaws.com:5432/cmsdb
spring.datasource.username=postgres
spring.datasource.password=daranexuscms
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
>>>>>>> 7658ebdaece6b63744f0a40ab852fbeedb3ee829


spring.devtools.restart.enabled=false

spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=false

logging.level.root=INFO

